
# Vector and matrix transpose


In [1]:
pip install torch

Defaulting to user installation because normal site-packages is not writeable
  Using cached torch-2.1.0-cp39-none-macosx_10_9_x86_64.whl (147.0 MB)
     |████████████████████████████████| 2.1 MB 1.2 MB/s eta 0:00:01
     |████████████████████████████████| 173 kB 11.6 MB/s eta 0:00:01
     |████████████████████████████████| 5.7 MB 11.5 MB/s eta 0:00:01
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Using cached MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_x86_64.whl (13 kB)
     |████████████████████████████████| 536 kB 11.6 MB/s eta 0:00:01
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 20.6 MB 11.5 MB/s eta 0:00:01
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
# import libraries
import numpy as np
import torch

# Using numpy

In [5]:
# create a vector
nv = np.array([ [1,2,3,4] ])
print(nv), print(' ')

# transpose it
print(nv.T), print(' ')

# transpose the transpose!
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [6]:
# repeat for a matrix
nM = np.array([ [1,2,3,4],
                [5,6,7,8] 
               ])
print(nM), print(' ')

# transpose it
print(nM.T), print(' ')

# transpose the transpose!
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


# Using pytorch

In [7]:
# create a vector
tv = torch.tensor([ [1,2,3,4] ])
print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transpose!
tvT = tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [8]:
# repeat for a matrix
tM = torch.tensor([ [1,2,3,4],[5,6,7,8] ])
print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transpose!
tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
#######

In [9]:
# examine data types
print(f'Variable nv is of type {type(nv)}')
print(f'Variable nM is of type {type(nM)}')
print(f'Variable tv is of type {type(tv)}')
print(f'Variable tM is of type {type(tM)}')

# nd for n-dimensional

Variable nv is of type <class 'numpy.ndarray'>
Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'torch.Tensor'>
Variable tM is of type <class 'torch.Tensor'>
