#  Matrix multiplication

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.76 -0.96  1.25 -0.14  0.91]
 [-0.17 -2.25 -0.75 -0.97  0.31]
 [-0.3  -2.55 -0.31 -0.55  0.16]]
 
[[-1.6  -1.39  1.68 -0.06]
 [-0.51 -0.79  0.09 -0.81]
 [ 2.18  1.14 -0.7   0.89]
 [ 1.34  0.66 -0.24  0.7 ]
 [ 0.69  0.5  -0.47  0.18]
 [-1.05  0.67  0.39  0.86]
 [-1.33  1.23  0.06  1.05]]


# Using pytorch

In [7]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-4.9800,  1.5700,  2.4400,  0.8300,  2.0800,  0.5800, -3.1200],
        [ 0.3400,  0.2700, -0.5200,  1.1100,  1.2000,  0.2400,  0.0500],
        [ 1.0900, -1.0100, -0.9300, -0.9100,  0.0000, -0.6200,  1.4800]],
       dtype=torch.float64)
 
tensor([[-4.9800,  1.5700,  2.4400,  0.8300,  2.0800,  0.5800, -3.1200],
        [ 0.3400,  0.2700, -0.5200,  1.1100,  1.2000,  0.2400,  0.0500],
        [ 1.0900, -1.0100, -0.9300, -0.9100,  0.0000, -0.6200,  1.4800]])
